
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 24;
  public static final int DIVISION = 29;
  public static final int SUMA = 26;
  public static final int MULTI = 28;
  public static final int ETIQUETAS = 8;
  public static final int EJECUTAR = 16;
  public static final int COMILLAS = 17;
  public static final int TIPO = 11;
  public static final int PORCENTAJE = 12;
  public static final int BARRAS = 3;
  public static final int VALORES = 9;
  public static final int COMA = 31;
  public static final int EOF = 0;
  public static final int TOTAL = 14;
  public static final int DEF = 2;
  public static final int PIE = 4;
  public static final int EXTRA = 15;
  public static final int CANTIDAD = 13;
  public static final int PARENTESIS_C = 23;
  public static final int error = 1;
  public static final int PARENTESIS_A = 22;
  public static final int LLAVE_C = 21;
  public static final int PUNTOCOMA = 25;
  public static final int LLAVE_A = 20;
  public static final int EJEY = 7;
  public static final int EJEX = 6;
  public static final int ENTERO = 30;
  public static final int CORCHETE_C = 19;
  public static final int CORCHETE_A = 18;
  public static final int UNIR = 10;
  public static final int TITULO = 5;
  public static final int RESTA = 27;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEF",
  "BARRAS",
  "PIE",
  "TITULO",
  "EJEX",
  "EJEY",
  "ETIQUETAS",
  "VALORES",
  "UNIR",
  "TIPO",
  "PORCENTAJE",
  "CANTIDAD",
  "TOTAL",
  "EXTRA",
  "EJECUTAR",
  "COMILLAS",
  "CORCHETE_A",
  "CORCHETE_C",
  "LLAVE_A",
  "LLAVE_C",
  "PARENTESIS_A",
  "PARENTESIS_C",
  "DOSPUNTOS",
  "PUNTOCOMA",
  "SUMA",
  "RESTA",
  "MULTI",
  "DIVISION",
  "ENTERO",
  "COMA"
  };
}

